version: "3.8"
services:
  graph-magic:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - neo4j
  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: none
